mpi_head:
    build: .
    # image: mpi
    ports: 
      - "22"
    links: 
      - mpi_node
    volumes:
      - /home/fan/docker.openmpi:/workspace
    # command: tail -F anything
mpi_node:
    build: .
    # image: mpi
    # command: tail -F anything
    volumes:
      - /home/fan/docker.openmpi:/workspace


# version: "2"

# services:
#   mpi_head:
#     build: .
#     # image: openmpi
#     ports: 
#       - "22"
#     links: 
#       - mpi_node
#     networks:
#       - net

#   mpi_node:
#     build: .
#     # image: openmpi
#     networks:
#       - net

# networks:
#   net:
#     driver: bridge
